export const GET_FILTERED_MOVIES_PENDING = "[T] GET_FILTERED_MOVIES_PENDING";
export const GET_FILTERED_MOVIES_FULFILLED =
  "[T] GET_FILTERED_MOVIES_FULFILLED";
export const GET_FILTERED_MOVIES_REJECTED = "[T] GET_FILTERED_MOVIES_REJECTED";
